.\"                                      Hey, EMACS: -*- nroff -*-
.TH GNOME-PIE 1 "November  12, 2011"
.SH NAME
gnome-pie \- visual application launcher for GNOME
.SH SYNOPSIS
.SY gnome-pie
.OP OPTIONS
.SH DESCRIPTION
\fBgnome-pie\fP is a radial visual application launcher for GNOME. It allows the
user to bind groups of frequently used applications to a ring that appears
when a hot key / mouse binding is triggered.
.SH OPTIONS
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS "Application Options:"
.TP
\fB\-o\fR, \fB\-\-open\fR=\fIID\fR
Open the Pie with the given ID
.TP
\fB\-r\fR, \fB\-\-reset\fR
Reset all options to default values
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH AUTHOR
gnome-pie was written by Simon Schneegans <code@simonschneegans.de>.
.PP
This manual page was written by Alessandro Ghedini <al3xbio@gmail.com>,
for the Debian project (and may be used by others).
